### ISSUE TITLE
related nvim issue

### ISSUE THREAD

**Issue by alok** [edluffy/origami.nvim#1]
i found this plugin from looking at random github projects and it's awesome.

i made an issue in a related vein a while ago that you may find interesting:

https://github.com/neovim/neovim/issues/8259

i know it's not a lot, but if you were willing to port some of this functionality into nvim's C code, i'd be willing to pay for it

**Comment by edluffy** [comment]
The linked issue relates to displaying kitty graphics via neovim’s terminal emulator, hologram currently works by passing the graphics ANSI escape codes directly over stdout.

In order for the former to work there would need to be support for the [kitty graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) in libvterm. This would need to be done *in addition* to reporting the screen sizes via the TIOCGWINSZ ioctl.

A potential workaround would be to have a way to wrap the escape sequences and have libvterm pass them to the real parent terminal where they would be handled instead. This would allow different image protocols (e.g sixels or iterm2) to work, with minimal changes to the neovim source code. I am happy to help on this but I need to take a look through :h dev to get an idea if this is feasible.
