### ISSUE TITLE
Examples in README does not works

### ISSUE THREAD

**Issue by kawarimidoll** [edluffy/origami.nvim#16]
I tried examples in README, but they caused error and cannot process images.

example in Usage section,
`require('hologram').add_image(0, img_path, 0, 0)`
→ `E5108: Error executing lua [string ":lua"]:1: attempt to call field 'add_image' (a nil value)`

example in image.lua API section,
`require('hologram.image'):new({ source = img_path, row = 0, col = 0, })`
→ `E5113: Error while calling lua chunk: ...config/nvim/plugged/hologram.nvim/lua/hologram/image.lua:32: Image source is not a valid string`

**Comment by jotamudo** [comment]
You should try doing `require('hologram').setup()` before executing the example code, it should work

**Comment by kawarimidoll** [comment]
> You should try doing require('hologram').setup() before executing the example code, it should work

It still raises same error 😢 


![画面収録 2022-08-11 7 56 09](https://user-images.githubusercontent.com/8146876/184037421-31c4b839-b8b6-400d-a625-b987ce065a02.gif)

In GIF above,

1. start Neovim by this setting (using vim-plug):
```vim
call plug#begin(stdpath('config') .. '/plugged')
Plug 'edluffy/hologram.nvim'
call plug#end()

lua require('hologram').setup({})
```

2. check `hologram.nvim` is loaded by `:PlugStatus`

3. run `require('hologram').add_image(0, '~/hologram-test/sample.png', 0, 0)`, then ↓
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'add_image' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by OmeletWithoutEgg** [comment]
The README document seems a little outdated (quite different from the main branch).
Currently, the following code works for me.

```lua
function Test()
    local Image = require('hologram.image')
    local source = '/home/user/Pictures/unknown.png'
    local img = Image:new(source, {})
    local buf = vim.api.nvim_get_current_buf()
    img:display(1, 1, buf, {})
end
```

BTW the autocmd of automatic displaying images in a markdown file is working correctly, just add the `auto_display = true` option.

```lua
require('hologram').setup { auto_display = true }
```

You'll need to launch neovim in a terminal emulator like kitty, as the README mentioned that hologram.nvim only supports Kitty Graphics Protocol at present.

**Comment by kawarimidoll** [comment]
Thank you for detailed answer, but the code does not work for me... 😭 

![画面収録 2022-08-15 17 16 23](https://user-images.githubusercontent.com/8146876/184601680-9cf695f5-ed5b-49ca-996a-3c9a3bf05c94.gif)

In GIF above,

1. start Neovim by this setting (`function HologramTest` is from @OmeletWithoutEgg 's answer, `sample.png` is my icon):
```vim
call plug#begin(stdpath('config') .. '/plugged')
Plug 'edluffy/hologram.nvim'
call plug#end()

lua << EOF
require('hologram').setup({auto_display = true})
function HologramTest()
  local Image = require('hologram.image')
  local source = vim.fn.expand('~/hologram-test/sample.png')
  local img = Image:new(source, {})
  local buf = vim.api.nvim_get_current_buf()
  img:display(1, 1, buf, {})
end
EOF
```

2. run `:lua HologramTest()` → image is not displayed 
3. open markdown file that contains `![img](./sample.png)` → image is not displayed, cursor flickers after entered visual mode

I'm using:
```
❯ kitty --version
kitty 0.25.2 created by Kovid Goyal

❯ nvim --version
NVIM v0.8.0-dev-853-g9a3877ff9
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by kawarimidoll@kawarimidoll-mba

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/opt/homebrew/Cellar/neovim/HEAD-9a3877f_1/share/nvim"

Run :checkhealth for more info
```

**Comment by edluffy** [comment]
@OmeletWithoutEgg This is correct - after adding inline image display I must have forgotten to change the example in the README - I have updated the docs now.

@kawarimidoll If I am correct in thinking this is an issue with macOS (just tested using a mac now and it seems to be) then the latest commit should fix your problem.

**Comment by kawarimidoll** [comment]
@edluffy The latest example in README shows image but that is narrow than I expected.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/8146876/184632871-7f6e1f5e-c890-4b5e-b02a-80b093b8cad1.png">

source image is square ↓
![sample](https://user-images.githubusercontent.com/8146876/184632920-4be918f1-5eec-452b-8678-f62188a0a004.png)

**Comment by edluffy** [comment]
Image should be full size with latest commit now. Although there might still be some scaling issues when scrolling...

**Comment by kawarimidoll** [comment]
The problem is fixed, nice work 🥰 
Thank you!

![SCR-20220816-iyd](https://user-images.githubusercontent.com/8146876/184799331-d2a4370c-78e1-4470-8ecd-141f6f267ec1.png)
