### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by GustavoPrietoP** [edluffy/origami.nvim#2]
Im currently using kitty and it seems like whenever i run the command `:lua require('hologram').add_image(0, vim.fn.stdpath("config") .. "/evil.png", 20, 50)` I get no error but i also get no image.  I wonder if you could help.

**Comment by GustavoPrietoP** [comment]
@edluffy hello?

**Comment by edluffy** [comment]
Not sure whats happening here. May work if you try and run the command via a keymap?

**Comment by GustavoPrietoP** [comment]
still nothing

**Comment by edluffy** [comment]
Is ImageMagick installed? - check by running `kitty +kitten icat .../evil.png` in a terminal instance which should produce a result.

**Comment by GustavoPrietoP** [comment]
yup

**Comment by GustavoPrietoP** [comment]
it displays the image correctly. It doesn't seem to give any errors just the image won't show. I'm not the only one having issues with it, a friend of mines also tested and it seems like it doesn't work for him as well

**Comment by mqrris** [comment]
Exactly the same with me.
