### ISSUE TITLE
Setup error: `/hologram/state.lua:36: bad argument #2 to 'ioctl' (cannot convert 'nil' to 'int')`

### ISSUE THREAD

**Issue by anoduck** [edluffy/origami.nvim#23]
Installed hologram through packer, but did not call the setup command, so as a result the command never became available to run it. Added the setup configuration, and receive the error every time my configuration file for nvim is loaded, and still command is not available. 

Error:
```lua
/hologram/state.lua:36: bad argument #2 to 'ioctl' (cannot convert 'nil' to 'int')
```

setup:
```lua
use {
  "edluffy/hologram.nvim",
  config = function()
    require("hologram").setup {
      auto_display = true
    }
  end
  }
```

**Comment by anoduck** [comment]
@edluffy No tomato.

**Comment by edluffy** [comment]
Hmm.... I can't seem to reproduce this. Can you tell me what OS you are using?

**Comment by anoduck** [comment]
> Hmm.... I can't seem to reproduce this. Can you tell me what OS you are using?

Ah, snap...my bad, Holmes. OpenBSD 7.2-CURRENT

Running hologram in neovim 0.8 (or whatever current is), in kitty 0.24.4, on OpenBSD.

Sorry, for making things difficult. Much love, for your work, though.
