### ISSUE TITLE
No image is shows, just base64 encoded strings

### ISSUE THREAD

**Issue by tzachar** [edluffy/origami.nvim#5]
Hi there.

Trying to load an image fails, with base64 text being inserted.
Using `kitty +kitten icat /tmp/1.png` does work though.

Using latest nvim nightly and kitty 0.22.2

**Comment by tzachar** [comment]
see #6

**Comment by nvr8** [comment]
Same for me, `kitty +kitten icat image.png` works, except when I try `..add_image(...)` in neovim nothing happens. No errors, no base64 string. I'm manually calling `setup()` as mentioned elsewhere. I print out some variables from the lua source, and all seems fine.
