### ISSUE TITLE
broken on HEAD neovim

### ISSUE THREAD

**Issue by goolord** [edluffy/origami.nvim#7]
expected lua number https://github.com/edluffy/hologram.nvim/blob/eb23c495bd512ce8d3f762a61f2f16df1e53633c/lua/hologram/image.lua#L20

i think the extmark api changed at some point

**Comment by nerdjp** [comment]
I solved this problem by calling `require('hologram').setup()` either manually or on packer config. Still, #5 happens to me now.

**Comment by romgrk** [comment]
Test with #8, it should fix the issue

**Comment by nerdjp** [comment]
Indeed #8 fixed the problem, now the plugin displays!
