### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by romgrk** [edluffy/origami.nvim#9]
Hey,

I have been doing a lot of work to expand the API of this plugin. I was wondering if you plan on actively continuing the development?
Would it also be possible to add a license to the project?

For reference, here is a branch with some changes I made: https://github.com/romgrk/hologram.nvim/tree/development
And here is a reddit post with a demo of them: https://www.reddit.com/r/neovim/comments/ssam1h/interminal_graphics_drawing_with_kitty/

Thanks

**Comment by edluffy** [comment]
Awesome!

I do plan on eventually starting working on this plugin again but I have been quite busy lately so i'm not sure when exactly. I'll add a license in the meantime. Thank you for taking an interest in this project!

**Comment by romgrk** [comment]
Cool :) Here is something that can be done with the new changes I made: https://github.com/MunifTanjim/nui.nvim/pull/107

Just a heads up, the changes are substantial: https://github.com/romgrk/hologram.nvim/tree/development

**Comment by edluffy** [comment]
I have taken a look through the changes you have made and everything looks good to me. Send in a PR when you are ready and I will merge :)

**Comment by romgrk** [comment]
See #12
